name: wordpress-playground
services:
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - 8001:80
    volumes:
      - ../wordpress:/var/www/html
    tty: true
    depends_on:
      - phpmyadmin

  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - 8002:80
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/volume:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u wp_user -pwp_pass"
      timeout: 5s
      interval: 5s
      retries: 10
