name: wordpress-playground
services:
  wordpress:
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - 8001:80
    volumes:
      - ../wordpress:/var/www/html
    tty: true

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/volume:/var/lib/mysql
