FROM wordpress:php8.4-apache

# 環境変数
## タイムゾーン
ENV TZ Asia/Tokyo
## Wordpress の環境変数
ENV WORDPRESS_DB_HOST db
ENV WORDPRESS_DB_USER wp_user
ENV WORDPRESS_DB_PASSWORD wp_pass
ENV WORDPRESS_DB_NAME wordpressdb
